replicaCount: 2

image:
  repository: nginx
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - paths:
        - path: /
          pathType: Prefix